sudo: false
dist: trusty
language: go
go:
- 1.8
before_script:
- wget https://releases.hashicorp.com/consul/0.7.5/consul_0.7.5_linux_amd64.zip
- unzip -d $GOPATH/bin consul_0.7.5_linux_amd64.zip
install:
- go get github.com/golang/lint/golint
- go get github.com/mitchellh/gox
script:
- make test
after_success:
- make release
notifications:
  email: true
deploy:
  provider: releases
  go: 1.8
  api_key:
    secure: JNEJATrWn9UJqKDG8SBORy4vJaoZmMakI0OYxbR9ScDOVfG+1Vj+EjGggkaW/oNUiPCHIdC1fu8EgYjqI/QOzbODU0rVVYgGNYsDEVamLpa5u6YpG0vyqMOMyPCV+9RxDGPGpWBP6XGo7+oitnxgo32XIPlGKG+NTODHQaOL20ZpmSG2AfyxDYXocHDUJvRZWjqN5GMId6tEqQytvE2PIueiHP6D8/btTtVjbPnPS+Q4wBDkRDzi/eYOd9UzhtswxcTTe8YBV3BnocH+n+uVj775rWSyCRQMqn1EFlK9chsAsdiVb81NtirbSVKWXKdlkyqvNHCHA1SZBZCmycKLQkJkqYFyvIa8W3I7Eoi847O3X+O8/krwPo4HNduswSRFI7ljlAaw74lbtAymGIQBusQ0QKGsBzfAVwju7WF5YwOklP7aR3pwHkQhlLqFS10l43ZPS/TAmEteAQCPNAg6BGuJ7FtkNI2lykElF+eg3DtsBxdQOLkpjM9EvuvJsk6Dgjg3A/JhWIaJBmwtJO+o+OIQyYXz0pyUn1ntJk+VBx81biqdxJMP2e8m392LalqQzucvpiSW/8u4/VGgnrPxMBQjjTEwM4i++PyiUsBpyyEORkJ6i2hGZ4HebrziZ9NjUbeClDozWph/4X0GkgiXQPxaaEz0RHD/bhYr5yMqBPU=
  file:
    - pkg/darwin-386-replicator
    - pkg/darwin-amd64-replicator
    - pkg/freebsd-386-replicator
    - pkg/freebsd-amd64-replicator
    - pkg/freebsd-arm-replicator
    - pkg/linux-386-replicator
    - pkg/linux-amd64-replicator
    - pkg/linux-arm-replicator
  skip_cleanup: true
  on:
    tags: true
